spring:
  datasource:
    url: jdbc:postgresql://207.180.200.244:5432/template

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

logging:
  file:
    name: C:/git/Personal/template/backend/logs/${spring.application.name}.log